service:
  name: sls-data-service

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

custom:
  serverless-offline:
    port: 3031
    host: 0.0.0.0

functions:
  api:
    handler: src/lambdas/index.server
    events:
      - http:
          method: post
          path: graphql
          cors: true
      - http:
          method: get
          path: verifyEmail/{userId}
          cors: true
          request:
            parameters:
              paths:
                userId: true
