export const IexCompanyDataKeys = {
	IEX_COMPANY__SYMBOL: "IEX_COMPANY_SYMBOL",
	IEX_COMPANY__COMPANY_NAME: "IEX_COMPANY_COMPANY_NAME",
	IEX_COMPANY__CEO: "IEX_COMPANY_CEO",
	IEX_COMPANY__EXCHANGE: "IEX_COMPANY_EXCHANGE",
	IEX_COMPANY__INDUSTRY: "IEX_COMPANY_INDUSTRY",
	IEX_COMPANY__WEBSITE: "IEX_COMPANY_WEBSITE",
	IEX_COMPANY__DESCRIPTION: "IEX_COMPANY_DESCRIPTION",
	IEX_COMPANY__ISSUE_TYPE: "IEX_COMPANY_ISSUE_TYPE",
	IEX_COMPANY__SECTOR: "IEX_COMPANY_SECTOR",
	IEX_COMPANY__SECURITY_NAME: "IEX_COMPANY_SECURITY_NAME",
	IEX_COMPANY__TAGS: "IEX_COMPANY_TAGS",
	IEX_COMPANY__EMPLOYEES: "IEX_COMPANY_EMPLOYEES"
};
