export const IexPreviousDayPriceDataKeys = {
	IEX_PREVIOUS_DAY_PRICE__SYMBOL: "IEX_PREVIOUS_DAY_PRICE__SYMBOL",
	IEX_PREVIOUS_DAY_PRICE__DATE: "IEX_PREVIOUS_DAY_PRICE__DATE",
	IEX_PREVIOUS_DAY_PRICE__OPEN: "IEX_PREVIOUS_DAY_PRICE__OPEN",
	IEX_PREVIOUS_DAY_PRICE__HIGH: "IEX_PREVIOUS_DAY_PRICE__HIGH",
	IEX_PREVIOUS_DAY_PRICE__LOW: "IEX_PREVIOUS_DAY_PRICE__LOW",
	IEX_PREVIOUS_DAY_PRICE__CLOSE: "IEX_PREVIOUS_DAY_PRICE__CLOSE",
	IEX_PREVIOUS_DAY_PRICE__VOLUME: "IEX_PREVIOUS_DAY_PRICE__VOLUME",
	IEX_PREVIOUS_DAY_PRICE__UNADJUSTED_VOLUME: "IEX_PREVIOUS_DAY_PRICE__UNADJUSTED_VOLUME",
	IEX_PREVIOUS_DAY_PRICE__CHANGE: "IEX_PREVIOUS_DAY_PRICE__CHANGE",
	IEX_PREVIOUS_DAY_PRICE__CHANGE_PERCENT: "IEX_PREVIOUS_DAY_PRICE__CHANGE_PERCENT"
};
